name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.1'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Build binaries
        run: |
          # Build taskfly CLI
          GOOS=linux GOARCH=amd64 go build -o taskfly-linux-amd64 ./cmd/taskfly
          GOOS=linux GOARCH=arm64 go build -o taskfly-linux-arm64 ./cmd/taskfly
          GOOS=darwin GOARCH=amd64 go build -o taskfly-darwin-amd64 ./cmd/taskfly
          GOOS=darwin GOARCH=arm64 go build -o taskfly-darwin-arm64 ./cmd/taskfly
          GOOS=windows GOARCH=amd64 go build -o taskfly-windows-amd64.exe ./cmd/taskfly

          # Build taskflyd daemon (go generate will handle agent builds including Windows)
          GOOS=linux GOARCH=amd64 go build -o taskflyd-linux-amd64 ./cmd/taskflyd
          GOOS=linux GOARCH=arm64 go build -o taskflyd-linux-arm64 ./cmd/taskflyd
          GOOS=darwin GOARCH=amd64 go build -o taskflyd-darwin-amd64 ./cmd/taskflyd
          GOOS=darwin GOARCH=arm64 go build -o taskflyd-darwin-arm64 ./cmd/taskflyd

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            taskfly-*
            taskflyd-*
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
